version: "3"

services:
  muzipiao:
    image: nginx
    volumes:
      - /root/muzipiao/nginx.conf:/etc/nginx/nginx.conf
      - /root/muzipiao/log/nginx:/var/log/nginx
      - /root/.acme.sh/muzipiao.github.io/:/etc/letsencrypt/live/muzipiao.github.io/
      - /root/muzipiao/_site:/var/www/muzipiao.github.io//public
    restart: always
    ports:
      - "80:80"
      - "443:443"

