version: "3"

services:
  muzipiao:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - /etc/letsencrypt/cocoafei.top:/etc/letsencrypt/live/cocoafei.top
      - /root/muzipiao/_site:/var/www/cocoafei.top/public
    restart: always
    ports:
      - "80:80"
      - "443:443"

