# 工作流程 (workflow) 名称
name: muzipiao.github.io/

# 触发条件
on:
  # 每天每 60 分钟运行一次此工作流
  schedule:
    - cron: '*/60 * * * *'

# 任务，一个工作流程由一个或多个任务 (job) 构成
jobs:
  # build 任务，这个工作流程包含一个名称为 "build" 的任务 (job)
  build:
    # 任务 (job) 运行的环境类型，运行在虚拟机环境 ubuntu-latest
    runs-on: ubuntu-latest

    # 步骤 (step) 表示将作为任务 (job) 一部分执行的一系列任务
    steps:
      # 第一步是获取源码，引用现成的检出 action，将代码检出到虚拟机上
      - uses: actions/checkout@v2
      
      # 运行一组 shell 名称，获取 muzipiao.github.io/ 的网站状态，并判断是否需要发送邮件
      - name: Get muzipiao.github.io/ response status code.
        run: |
          export status_code=$(curl -I -m 15 -s -w "%{http_code}\n" -o /dev/null  muzipiao.github.io/)
          python ./email_status.py ${{secrets.MAIL_USERNAME}} ${{secrets.MAIL_PASSWORD}} $status_code
